Upgrade (13 -> 14) and adapt config (PASSWORD -> PASSWORD_HASH)
It should be noted that v14 doesn't seem to work correctly.
Logging in causes:

> ReferenceError: restoreConfig is not defined